# site settings
title: Scotty Skidmore
subtitle: Data Scientist
email: scotty.skidmore@gmail.com
description: Sydney Based Data Scientiest and Python Scripter
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
#url: scottyskidmore.com
author: Scotty Skidmore
street_address: Peir 8/9, Lot 2, 23 Hickson Rd
city: Millers Point
state: NSW
zip_code: 2000
country: Australia
phone: 0431 577 756

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url: https://www.facebook.com/scotty.skidmore13
github_url: https://github.com/scottyskid
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/scotty-skidmore-5b528394/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
